# Generated by Django 4.2.7 on 2023-11-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_order_date_order_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Order at'),
        ),
    ]
