# Generated by Django 4.2.7 on 2023-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_order_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price in sum.', max_digits=20, null=True, verbose_name='Total price'),
        ),
    ]
